- name: Clone repo cachet apps
  git:
    repo: "{{ git_repo }}"
    dest: /home/ubuntu/{{ customer_name }}

- name: Create docker-compose file
  copy:
    dest: /home/ubuntu/{{ customer_name }}/cachet/docker-compose.yml
    content: |
      version: "3"
      services:
        {{ customer_name }}-postgres:
          image: postgres:9.5
          volumes:
            - /var/lib/postgresql/data
          environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
          restart: always
        {{ customer_name }}-cachet:
          build:
            context: .
            args:
              - cachet_ver=v2.3.15
          ports:
            - {{ nginx_port }}:{{ nginx_port }}
          links:
            - {{ customer_name }}-postgres:{{ customer_name }}-postgres
          environment:
            - DB_DRIVER=pgsql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - DB_PREFIX=chq_
            - APP_KEY=${APP_KEY:-null}
            - APP_LOG=errorlog
            - DEBUG=false
          depends_on:
            - {{ customer_name }}-postgres
          restart: on-failure

- name: Paste DOCKERFILE
  template:
    src: ./roles/cachet/templates/dockerfile.j2
    dest: /home/ubuntu/{{ customer_name }}/cachet/Dockerfile
    become: yes

- name: Paste NGINX config files
  template:
    src: ./roles/cachet/templates/nginx.conf.j2
    dest: /home/ubuntu/{{ customer_name }}/cachet/conf/nginx-site.conf
    become: yes
