    - name: copy the nginx config file
      copy:
        src: ./roles/nginx/templates/customer_name.conf.j2
        dest: /etc/nginx/conf.d/${customer_name}.conf
      become: yes
    # - name: create symlink
    #   file:
    #     src: /etc/nginx/sites-available/static_site.cfg
    #     dest: /etc/nginx/sites-enabled/default
    #     state: link
    #   become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
