- name: Paste NGINX config files
  template:
    src: ./roles/nginx/templates/config.j2
    dest: /etc/nginx/conf.d/{{ customer_name }}.conf
  become: yes

- name: Nginx reload
  command: nginx -s reload
  
#- name: create symlink
#   file:
#     src: /etc/nginx/sites-available/static_site.cfg
#     dest: /etc/nginx/sites-enabled/default
#     state: link
#   become: yes

# - name: restart nginx
#   service:
#    name: nginx
#    state: restarted
#   become: yes
