version: "3"

services:
  ${CUSTOMER_PG}:
    image: postgres:9.5
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  ${CUSTOMER_CH}:
    build:
      context: .
      args:
        - cachet_ver=v2.3.15
    ports:
      - ${PORT}:${PORT}
    links:
      - ${CUSTOMER_PG}:${CUSTOMER_PG}
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - DEBUG=false
    depends_on:
      - ${CUSTOMER_PG}
    restart: on-failure